### ISSUE TITLE
I create Flatpak for Codelite, interest?

### ISSUE THREAD

**Issue by kevinsmia1939** [eranif/codelite#2687]
Hi,

I just package Codelite as Flatpak.
https://github.com/kevinsmia1939/org.codelite.Codelite
```
Flatpak is a utility for software deployment and package management for Linux. It is advertised as offering a sandbox environment in which users can run application software in isolation from the rest of the system.

Flatpak was developed as part of the freedesktop.org project (formerly known as X Desktop Group or XDG) and was originally called xdg-app.
-wikipedia
```
https://www.flatpak.org/

I would like to upload this to Flathub eventually.
https://flathub.org/home
https://github.com/flathub

If Flathub maintainer like it, they would likely ask you to be the maintainer instead.

Right now it build and launch just fine, I have not tried any coding and compile on it. (I know nothing about coding)
It have to be test and refine sandbox permission and remove unnecessary files.

It can be build and run with instruction below.

Install flatpak-builder 
`sudo apt install flatpak-builder`
Build
`flatpak-builder --install --user build org.codelite.Codelite.yaml --force-clean`
Run
`flatpak run org.codelite.Codelite`

What do you think?
Thanks.

**Comment by kevinsmia1939** [comment]
One issue I found is text color is white. I try changing the theme but the text color does not change. Anyone know?

https://imgur.com/eCLylYV

**Comment by eranif** [comment]
which version of CodeLite did you pack?

**Comment by kevinsmia1939** [comment]
> which version of CodeLite did you pack?

15.0

**Comment by dghart** [comment]
Hi,

Thank you for providing this. I've spent time (teaching myself the flatpak basics, and) testing it on debian 10 (buster), with mixed results. The good news:

1) Your yaml file works to build CodeLite 15.0. It also works to build 15.0.1 after the following changes to the last 2 lines:
`        url: https://github.com/eranif/codelite/archive/15.0.1.tar.gz`
`        sha256: 5cc6ceb34148da063653fb4937146972f95876cca0e39459810e5e1ccda51ecd`
2) The resulting binary runs normally; but see below.
3) I've created a repo for the 15.0.1 build. After testing it locally, I've temporarily uploaded it to: https://repos.codelite.org/Flathub/CodeliteRepo
4) While it was local, I could use that repo to install and run CodeLite on ubuntu 20.10, fedora 32, Mandriva 4.1 and openSUSE 15.2. (However older distro/versions failed with 'Unacceptable TLS certificate' errors.)

The bad news:
1) The binary runs, but it can't access enough of the file system to be useful. In particular, it can't find the system's wxWidgets install, so it fails to build the commonest projects.
IIUC that should have been fixed by adding to the yaml file's finish-args the line:
`  - --filesystem=/usr/path:ro`
However that doesn't work for me. I'd be grateful for your suggestions about this.
2) There is a problem with the repo that I created. Though I could remote-add it successfully when using file:///path/to/local/webserver/..., the same address using http://, either to my webserver or to above link, will fail with the error:
'Unable to load summary from remote CodeliteFlathub: Remote listing for CodeliteFlathub not available; server has no summary file. Check the URL passed to remote-add was valid.'
despite the summary file existing.
Again I'd be grateful for your help in fixing this.

Regards,

David

**Comment by kevinsmia1939** [comment]
@dghart
If I understand flatpak correctly, it is normal for flatpak apss to not be able to access root directory and thus, system installed wxWidgets by default. I will have to install wxWidgets to gether with Cidelite in Flatpak manifest. Could you link me to source code of the wxWidgets?

About the second issue, I don't know.

**Comment by dghart** [comment]
>it is normal for flatpak apps to not be able to access root directory
I thought adding:
`- --filesystem=/usr/path:ro`
would allow this. Am I wrong? If so, what _does_ that do?

>Could you link me to source code of the wxWidgets?
https://www.wxwidgets.org/downloads/
wx3.0.5 is the current stable release. However all the main distros provide their own packages.

**Comment by kevinsmia1939** [comment]
> > it is normal for flatpak apps to not be able to access root directory
> 
> I thought adding:
> `- --filesystem=/usr/path:ro`
> would allow this. Am I wrong? If so, what _does_ that do?
> Edit: And removing the :ro didn't help.
> 
> > Could you link me to source code of the wxWidgets?
> 
> https://www.wxwidgets.org/downloads/
> wx3.0.5 is the current stable release. However all the main distros provide their own packages.

wxWidgets is already included in Flatpak. I think maybe cleanup bin might broke it. Just remove the cleanup bin part under wxWidgets and see if it work.

**Comment by kevinsmia1939** [comment]
> > it is normal for flatpak apps to not be able to access root directory
> 
> I thought adding:
> `- --filesystem=/usr/path:ro`
> would allow this. Am I wrong? If so, what _does_ that do?
> Edit: And removing the :ro didn't help.
> 
> > Could you link me to source code of the wxWidgets?
> 
> https://www.wxwidgets.org/downloads/
> wx3.0.5 is the current stable release. However all the main distros provide their own packages.

wxWidgets is already included in Flatpak. I think maybe cleanup bin might broke it. Just remove the cleanup bin part under wxWidgets and see if it work.

**Comment by dghart** [comment]
>Just remove the cleanup bin part under wxWidgets

That worked. I can now build simple programs.

OTOH my first attempt at _running_ the program failed. That's because it tried to run it in a system terminal, which lives in /usr/bin/. However, after changing the preferred terminal to the one provided by CodeLite, the program ran normally :) .

However that's not ideal; and I expect that more 'normal use' testing will disclose other similar problems. How do other flatpak programs cope with this?

**Comment by kevinsmia1939** [comment]
> > Just remove the cleanup bin part under wxWidgets
> 
> That worked. I can now build simple programs.
> 
> OTOH my first attempt at _running_ the program failed. That's because it tried to run it in a system terminal, which lives in /usr/bin/. However, after changing the preferred terminal to the one provided by CodeLite, the program ran normally :) .
> 
> Still, that's not ideal; and I expect that more 'normal use' testing will disclose other similar problems. How do other flatpak programs cope with this?

Does it show error log when it fail to run in system terminal?
I think Flatpak apps can run as normal use, just a matter of refining sandbox permissions to allow access to certain part of the system. By default, it does not allow much, it have to be explicitly given the permission unlike how we normally install packages which give more access.

**Comment by kevinsmia1939** [comment]
Here is some flatpak mainfest for code block, visualstudio code, sublime

https://github.com/flathub/org.codeblocks.codeblocks/blob/master/org.codeblocks.codeblocks.json
https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml
https://github.com/flathub/com.sublimemerge.App/blob/master/com.sublimemerge.App.yaml

**Comment by dghart** [comment]
>Does it show error log when it fail to run in system terminal?

It shows CodeLite's standard 'Can't find {terminal-name}' error, which is what is expected if there is no access there. However the situation is probably more complicated: to find the terminal, CodeLite runs a script, and it might be the script that is inaccessible.

I've also found that I can't get CodeLite to run a 'locally-installed' gdb. However it _can_ run /usr/bin/gdb :/
Yet I read in https://docs.flatpak.org/en/latest/sandbox-permissions.html that /usr/  is black-listed, which I presume means that `--filesystem=/usr/path`will not work...

>Here is some flatpak mainfest for code block, visualstudio code, sublime

Thank you. However I can't see that they do anything very different.

**Comment by kevinsmia1939** [comment]
> > Does it show error log when it fail to run in system terminal?
> 
> It shows CodeLite's standard 'Can't find {terminal-name}' error, which is what is expected if there is no access there. However the situation is probably more complicated: to find the terminal, CodeLite runs a script, and it might be the script that is inaccessible.
> 
> I've also found that I can't get CodeLite to run a 'locally-installed' gdb. However it _can_ run /usr/bin/gdb :/
> Yet I read in https://docs.flatpak.org/en/latest/sandbox-permissions.html that /usr/ is black-listed, which I presume means that `--filesystem=/usr/path`will not work...
> 
> > Here is some flatpak mainfest for code block, visualstudio code, sublime
> 
> Thank you. However I can't see that they do anything very different.

I might have to include gdb in flatpak manifest too as well.

**Comment by dghart** [comment]
>Not sure what to do about the gdb, I have to include gdb in flatpak manifest too as well?

No need: CodeLite _can_ find it; it's just that some people (me) will prefer to run the latest gdb version, not the installed one.

The problem is not really gdb, but the other terminals (konsole, xterm, lxterminal...) that the user may want to use. Of course that is not a pass/fail issue, just annoying. But it does illustrate possible problems.

And I only use CodeLite for C++ projects. It also does PHP etc, which I've not tested...

**Comment by kevinsmia1939** [comment]
> > Not sure what to do about the gdb, I have to include gdb in flatpak manifest too as well?
> 
> No need: CodeLite _can_ find it; it's just that some people (me) will prefer to run the latest gdb version, not the installed one.
> 
> The problem is not really gdb, but the other terminals (konsole, xterm, lxterminal...) that the user may want to use. Of course that is not a pass/fail issue, just annoying. But it does illustrate possible problems.
> 
> And I only use CodeLite for C++ projects. It also does PHP etc, which I've not tested...

Flatpak is well known to have problem with command line apps. It  is usually use for GUI apps. But since Codelite also have cli feature, it might be a problem.
https://github.com/flatpak/flatpak/issues/1188

**Comment by bztd** [comment]
Hi, I've added a wrapper for CodeLite to the manifest so it can use SDK plugins. I've also added a plugin that can be installed to support other tools like wxWidgets and how-tos. The problem is that there's no terminal, and applications won't run. Most options have too many dependencies, like gnome-terminal. Is there a way to use Termite or VTE?

**Comment by bztd** [comment]
the manifesto:

https://github.com/bztd/flathub/tree/CdLite

**Comment by bztd** [comment]
I've added a terminal to the package, I think it's ready to be published, I've already made the request, if there are any suggestions or anyone wants to maintain the package, I'll be happy to hear it.

**Comment by bztd** [comment]
It seems there's a policy in Flatpak that applications like CodeLite must be explicitly supported by the development team.
I'll paste the manifest I created in case it helps:

```
app-id: org.codelite.codelite
runtime: org.freedesktop.Sdk
sdk: org.freedesktop.Sdk
runtime-version: '24.08'
command: codelite

rename-desktop-file: codelite.desktop
rename-icon: codelite

finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --allow=devel
  - --filesystem=xdg-documents
  - --persist=.codelite
  - --env=PATH=/usr/bin:/app/bin:/app/plugins/devtools/bin
  - --env=FLATPAK_ENABLE_SDK_EXT=*

add-extensions:
  org.codeblocks.codeblocks.Plugin:
    version: stable
    directory: plugins
    subdirectories: true
    no-autodownload: true
    autodelete: true
    add-ld-path: lib

modules:

  - name: devTools
    buildsystem: simple
    build-commands:
      - install -d /app/plugins

  - name: libssh
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DWITH_GSSAPI=OFF
      - -DWITH_EXAMPLES=OFF
    cleanup:
      - /include
    sources:
      - type: archive
        url: https://www.libssh.org/files/0.11/libssh-0.11.1.tar.xz
        sha256: 14b7dcc72e91e08151c58b981a7b570ab2663f630e7d2837645d5a9c612c1b79

  - name: wxwidgets
    buildsystem: autotools
    no-autogen: true
    config-opts:
      - --with-gtk=3
      - --disable-webview
    cleanup:
      - /bin
      - /include
      - /lib/wx
      - /share/aclocal
      - /share/bakefile
    sources:
      - type: archive
        url: https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.6/wxWidgets-3.2.6.tar.bz2
        sha256: 939e5b77ddc5b6092d1d7d29491fe67010a2433cf9b9c0d841ee4d04acb9dce7

  - name: cppcheck
    buildsystem: cmake-ninja
    cleanup:
      - /include
      - /lib/pkgconfig
      - /share/applications
      - /share/man
      - '*.a'
    sources:
      - type: archive
        url: https://sourceforge.net/projects/cppcheck/files/cppcheck/2.16/cppcheck-2.16.0.tar.gz
        sha256: f1a97c8cef5ee9d0abb57e9244549d4fe18d4ecac80cf82e250d1fc5f38b1501
        
  - name: vte
    buildsystem: meson
    config-opts:
      - -Ddocs=false
      - -Dvapi=false
      - -Dgir=false
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/vte.git
        tag: 0.72.4
        commit: 45d815431c08ff5a3cf076cde5edd43054773c4a

  - name: codelite
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCL_PREFIX=/app
    post-install:
      - mv /app/bin/codelite /app/bin/codelite-bin
      - install -Dm755 ../gnome-terminal -t /app/bin/
    sources:
      - type: git
        url: https://github.com/eranif/codelite.git
        tag: 18.1.0
        commit: 15aff6f1b7bac11572190407a533d83a59d12aee
      - type: patch
        path: org.codelite.codelite.metainfo.xml.patch
      - type: file
        path: gnome-terminal

  - name: ide-flatpak-wrapper
    buildsystem: meson
    config-opts:
      - -Deditor_binary=/app/bin/codelite-bin
      - -Deditor_title=Codelite IDE
      - -Dprogram_name=codelite
      - -Dfirst_run_template=ide-first-run.txt
      - -Dsdk_version=24.08
    sources:
      - type: git
        url: https://github.com/flathub/ide-flatpak-wrapper.git
        commit: 445fdd20b2f083fe12ac9ac61c1a30864da8a8d1
      - type: file
        path: ide-first-run.txt
```
